#!/bin/bash
# /etc/init.d/htemp
#

### BEGIN INIT INFO
# Provides: htemp
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: Test daemon process
# Description:    Runs up the test daemon process
### END INIT INFO

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon
    python /usr/share/htemp/htemp.py start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    python /usr/share/htemp/htemp.py stop
    ;;
  restart)
    echo "Restarting server"
    python /usr/share/htemp/htemp.py restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/htemp {start|stop|restart}"
    exit 1
    ;;
esac
exit 0

